### ISSUE TITLE
Add Book - Search Internet

### ISSUE THREAD

**Issue by vrajs5** [eleybourn/Book-Catalogue#700] opened 2015-10-29 05:08 UTC
It usually happens that when I am adding book using 'Search Internet' option, it usually takes first hit on net and add it. This ends up something completely different than expected. And specially if user search book from particular author it takes most search book of that author from internet. I would suggest once user ask app to search on internet, app should show search results to user, lets say 10 books from on net, from which user can select desired one to add to bookshelf. Right now I am not able to use this feature at all.

**Comment by Grunthos** [comment] 2015-10-29 06:44
Duplicate of https://github.com/eleybourn/Book-Catalogue/issues/284

**Closed by Grunthos** 2015-10-29 06:44 UTC
