### ISSUE TITLE
No export file found

### ISSUE THREAD

**Issue by krystal16** [eleybourn/Book-Catalogue#816] opened 2019-04-14 21:11 UTC
No export files found.  

I exported my file to a csv, emailed it to myself last week with my old phone.  Got a new phone today, installed Book Catalogue (Moto G6 Play), saved the export.csv file to the Book Catalogue folder in My Files (there are four csv files  plus .nomedia bookCataloguebookCatalogueDbEx (cuts off on my screen) and another that looks that same that is 205k)

I have exported, the file is one of of the four listed above, but it won't even see that one to import it again.  Please help.
![57004908_1287695301398769_2003259359164891136_n](https://user-images.githubusercontent.com/49622686/56099241-4aa84780-5ed8-11e9-97c9-759a483bac42.png)

**Comment by Grunthos** [comment] 2019-09-28 06:56
Duplicate of Issue 817

**Closed by Grunthos** 2019-09-28 06:56 UTC
