### ISSUE TITLE
add bibtex support for im/export

### ISSUE THREAD

**Issue by KyGITyK** [eleybourn/Book-Catalogue#687] opened 2015-08-26 18:30 UTC
bibtex is a common format, that is genius for making libraries/databases and can be updated via other sources like JabRef etc.

**Comment by Grunthos** [comment] 2015-08-29 01:33
Duplicate of https://github.com/eleybourn/Book-Catalogue/issues/308

**Closed by Grunthos** 2015-08-29 01:33 UTC
